language: ruby
rvm:
  - 2.0.0
services:
  - postgresql
  - redis
before_script:
  - psql -c 'create database radioxide_test;' -U postgres
  - 'echo "--\ntest:\n  adapter: postgresql\n  database: radioxide_test\n  username: postgres" > /home/travis/build/elthariel/radioxide/config/database.yml'
  - cat -e /home/travis/build/elthariel/radioxide/config/database.yml
